preprocessing:
  map_bins_columns:
    age: [35, 60]
    MonthlyIncome: [4000, 8000]
    NumberOfDependents: [0, 6]
  drop_columns: [ 'id']
  train_path: ../data/raw/train.csv
  unique_values_path: ../data/processed/unique_values.json
  train_path_proc: ../data/processed/train.csv
  test_path_proc: ../data/processed/test.csv
  test_size: 0.25
  target_column: SeriousDlqin2yrs
  random_state: 10

train:
  n_trials: 10
  n_folds: 5
  random_state: 10
  target_column: SeriousDlqin2yrs
  model_path: ../models/model_lgb.joblib
  study_path: ../models/study.joblib
  metrics_path: ../report/metrics.json
  params_path: ../report/best_params.json

evaluate:
  predict_path: ../data/check/test.csv

endpoints:
  train: 'http://fastapi:8000/train'
  prediction_input: 'http://fastapi:8000/predict_input'
  prediction_from_file: 'http://fastapi:8000/predict'
  # train: 'http://localhost:8000/train'
  # prediction_input: 'http://localhost:8000/predict_input'
  # prediction_from_file: 'http://localhost:8000/predict'
